// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFjEP4Y0RtdSu3VrgMG60ToycuWhb6Wg4',
    appId: '1:933314969288:web:0d9703a891406fc4766ffd',
    messagingSenderId: '933314969288',
    projectId: 'scam-alert-7749c',
    authDomain: 'scam-alert-7749c.firebaseapp.com',
    storageBucket: 'scam-alert-7749c.appspot.com',
    measurementId: 'G-23PB2ZN5NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5jLJVUi9GBCNGHUPIWgDm9VeRaBwF7WA',
    appId: '1:933314969288:android:a491aa6730e0c61a766ffd',
    messagingSenderId: '933314969288',
    projectId: 'scam-alert-7749c',
    storageBucket: 'scam-alert-7749c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA3UkeiaRVWS-PPtZ0iKkMgzWjxp8LUlo',
    appId: '1:933314969288:ios:d0f64b81723a86d3766ffd',
    messagingSenderId: '933314969288',
    projectId: 'scam-alert-7749c',
    storageBucket: 'scam-alert-7749c.appspot.com',
    iosBundleId: 'com.example.scamAlert',
  );
}
